spring:
  datasource:
    url: jdbc:postgresql://dpg-d8ud28e8bjmc73dmmfug-a:5432/sanctuarity
    username: sanctuarity_user
    password: tnG5T7W6G7TWjMaXgjEQoz3aRbLiQUEQ
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2}
    expiration-ms: 86400000
  bank:
    name: "Sanctuary of Equilibrium"
    code: "SOEB"
    swift: "SOEBINBB"
    rbi-license: "RBI-L-2024-SOEB-001"
